// 业务路由聚合器。各资源路由逐个接入。
import { inquiriesRoutes } from './inquiries.js';
import { seoWeeksRoutes } from './seoWeeks.js';
import { semWeeksRoutes } from './semWeeks.js';
import { kpiRoutes } from './kpi.js';
import { negKeywordsRoutes } from './negKeywords.js';
import { adCreativesRoutes } from './adCreatives.js';
import { rankSnapshotsRoutes } from './rankSnapshots.js';
import { keywordsRoutes } from './keywords.js';
import { fixesRoutes } from './fixes.js';
import { loopItemsRoutes } from './loopItems.js';
import { aiRoutes } from './ai.js';
import { syncRoutes } from './sync.js';
import { settingsRoutes } from './settings.js';
import { marketRoutes } from './market.js';
import { overviewRoutes } from './overview.js';
import { weeklyReportsRoutes } from './weeklyReports.js';
import { contentAssetsRoutes } from './contentAssets.js';
import { ga4Routes } from './ga4.js';
import { dataSourcesRoutes } from './dataSources.js';
import { sopRoutes } from './sop.js';
import { taskCheckinsRoutes } from './taskCheckins.js';
import { googleRoutes } from './google.js';
import { diagnosticsRoutes } from './diagnostics.js';
import { attributionRoutes } from './attribution.js';
import { hermesRoutes } from './hermes.js';
import { dataFreshnessRoutes } from './dataFreshness.js';
import { hermesActionsRoutes } from './hermesActions.js';

export async function registerRoutes(app) {
  await app.register(inquiriesRoutes);
  await app.register(seoWeeksRoutes);
  await app.register(semWeeksRoutes);
  await app.register(kpiRoutes);
  await app.register(negKeywordsRoutes);
  await app.register(adCreativesRoutes);
  await app.register(rankSnapshotsRoutes);
  await app.register(keywordsRoutes);
  await app.register(fixesRoutes);
  await app.register(loopItemsRoutes);
  await app.register(aiRoutes);
  await app.register(syncRoutes);
  await app.register(settingsRoutes);
  await app.register(marketRoutes);
  await app.register(overviewRoutes);
  await app.register(weeklyReportsRoutes);
  await app.register(contentAssetsRoutes);
  await app.register(ga4Routes);
  await app.register(dataSourcesRoutes);
  await app.register(sopRoutes);
  await app.register(taskCheckinsRoutes);
  await app.register(googleRoutes);
  await app.register(diagnosticsRoutes);
  await app.register(attributionRoutes);
  await app.register(hermesRoutes);
  await app.register(dataFreshnessRoutes);
  await app.register(hermesActionsRoutes);
}
